<?php
/* %NameSpace% */

use le0daniel\System\App;
use le0daniel\System\Helpers\Language;
use le0daniel\System\Helpers\Path;
/* %UseWPExtender% */

/**
 * Basic Variables, needed here
 *
 * The Theme Name should be the same as the theme folder name!
 */

/* %ThemeName% */
$view_root  = __DIR__.'/resources/views';

/**
 * Run the Application
 * It's only necessary to run the app if you need additional features like
 * Routing and stuff like that.
 *
 * The app is initialized in the mu-plugins --> system-booter.php
 */
if( ! class_exists(App::class) ){
	echo 'Application not loaded!';
	die();
}

/**
 * Change root dir if needed!
 * Should be set outside the web dir!
 *
 * For more advanced features run the app!
 *
 * So disable it if you are not sure!
 */
App::init($GLOBALS['root_dir']);
//app()->run();

/**
 * Load the translation file and set the translation namespace
 */
load_theme_textdomain($theme_name,__DIR__.'/resources/lang/');
Language::$translation_context = $theme_name;
Path::$theme_dirname = $theme_name;

/* Lets WP Handle the Title */
//add_theme_support( 'title-tag' );

/* Setup HTML 5 Support */
//add_theme_support( 'html5', [ 'search-form', 'comment-form', 'comment-list', 'gallery', 'caption', ]);

/* Configure the view */
view()
	->setRootDir($view_root)
	->setPlainCache(false)
	->addIncludePath($view_root.'/components','c')
	->addIncludePath($view_root.'/pages',     'pages')
	->addIncludePath($view_root.'/layouts',   'layouts')
	->addIncludePath($view_root.'/shortcodes','shorts')

	/**
	 * Add The context, default is wp.context
	 * --> \System\Wordpress\Context good point to extend
	 *
	 * Must implement CastArray contract
	 *
	 * Is lazy loaded! Resolved when needed!
	 * will be resolve container!
	 */
	//->addContext( 'wp.context' )

	/* Set what is supported! */
	->share('supports',[
		'apple'=>false,
		'microsoft_tiles'=>false,
		'social_tags'=>false,
	]);

/**
 * Extend Wordpress
 *
 * Use this to include Shortcuts and Visual composer
 * Components generated by the framework
 *
 * if you don't use any of them, you can comment
 * out this line!
 */
resolve(WordPressExtender::class)->boot();